dist: xenial
language: python

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libspatialindex-c4v5 libspatialindex-dev

install:
  - pip install requirements.txt
  - pip install .
  - pip install pytest

script:
  - python -m pytest