name: trackintel_docs
channels:
  - conda-forge
  - defaults
dependencies:
- python=3.8
- numpy
- matplotlib
- pandas
- geopandas
- gdal
- rtree
- scikit-learn
- networkx
- pint
- pip
- geoalchemy2
- osmnx
- psycopg2
- imageio
- sphinx
- sphinx_rtd_theme
- pip:
  - simplification