name: trackintel_docs
channels:
  - conda-forge
  - defaults
dependencies:
- python=3.8
- numpy
- matplotlib
- pandas
- geopandas
- scikit-learn
- networkx
- pint
- pip
- geoalchemy2
- osmnx
- psycopg2
- imageio
- sphinx
- pydata-sphinx-theme
- pip:
  - simplification
  - sphinx-toggleprompt