name: trackintel_docs
channels:
  - conda-forge
  - defaults
dependencies:
# - python=3.8
- geopandas
- pygeos
- pip:
  - numpy
  - matplotlib
  - pandas
  - scikit-learn
  - networkx
  - pint
  - geoalchemy2
  - osmnx
  - psycopg2
  - sphinx
  - sphinx_rtd_theme
  - tqdm
  - similaritymeasures
  
